#!/bin/bash

case "$1" in
    start)
        systemctl start bot.service
        ;;
    stop)
        systemctl stop bot.service
        ;;
    restart)
        systemctl restart bot.service
        ;;
    *)
        echo "Usage: bot {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
